In [1]:
import numpy as np


In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

### 1. How many negative numbers are there?

In [4]:
a[a<0]

array([-2, -1, -6, -7])

In [5]:
print(a[a < 0])
len(a[a<0])

[-2 -1 -6 -7]


4

### 2. How many positive numbers are there?


In [7]:
a[a>0]

array([ 4, 10, 12, 23,  3])

In [8]:
print(a[a > 0])
len(a[a>0])

[ 4 10 12 23  3]


5

### 3. How many even positive numbers are there?

In [10]:
a[(a > 0) & (a % 2 ==0)]

array([ 4, 10, 12])

In [11]:
len(a[(a > 0) & (a % 2 ==0)])

3

### 4.  If you were to add 3 to each data point, how many positive numbers would there be?

In [13]:
b=a+3
b[b>0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [14]:
len(b[b>0])

10

### 5. If you squared each number, what would the new mean and standard deviation be?

In [16]:
c = (a **2)
c.mean(), c.std()

(74.0, 144.0243035046516)

### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [18]:
np.mean(a)

3.0

In [19]:
a -=3 
a


array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [20]:
a.mean()

0.0

### 7. Calculate the z-score for each data point. Recall that the z-score is given by:

In [22]:
zscores = (a - a.mean()) / a.std()
zscores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [23]:
a.std()

8.06225774829855

In [24]:
20 / 2.48

8.064516129032258

### 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.
### Life w/o numpy to life with numpy
### Setup 1
### Use python's built in functionality/operators to determine the following:
### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [103]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [30]:
sum_of_a = sum(a)
sum_of_a

55

### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [32]:
min_of_a = min(a)
min_of_a

1

### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [34]:
max_of_a = max(a)
max_of_a

10

### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [36]:
mean_of_a = sum(a) / len(a)
mean_of_a

5.5

### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [38]:
product_of_a = 1
for n in a:
    product_of_a *= n

product_of_a

3628800

### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [40]:
squares_of_a = [n ** 2 for n in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [42]:
odds_in_a = [n for n in a if n % 2 != 0]
odds_in_a

[1, 3, 5, 7, 9]

### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [44]:
evens_in_a = [n for n in a if n % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
### Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.


In [47]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [48]:
b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [51]:
solutions = {
    "sum": b.sum(),
    "min": b.min(),
    "max": b.max(),
    "mean": b.mean(),
    "squares": b**2,
    "product": b.prod()
}
solutions

{'sum': 33,
 'min': 3,
 'max': 8,
 'mean': 5.5,
 'squares': array([[ 9, 16, 25],
        [36, 49, 64]]),
 'product': 20160}

### Exercise 9 - print out the shape of the array b.

In [53]:
b.shape

(2, 3)

### Exercise 10 - transpose the array b.

In [55]:
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [57]:
b.reshape(1, 6)

array([[3, 4, 5, 6, 7, 8]])

### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [59]:
b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Setup 3
### HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
### Exercise 1 - Find the min, max, sum, and product of c.

In [61]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [62]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Exercise 2 - Determine the standard deviation of c.

In [64]:
c.std()

2.581988897471611

### Exercise 3 - Determine the variance of c.

In [66]:
c.var()

6.666666666666667

### Exercise 4 - Print out the shape of the array c

In [68]:
c.shape

(3, 3)

### Exercise 5 - Transpose c and print out transposed result.

In [70]:
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [105]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Exercise 6 - Get the dot product of the array c with c. 

In [72]:
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [74]:
c * c.T

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [75]:
(c * c.T).sum()

261

### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [77]:
(c * c.T).prod()

131681894400

### Setup 4
### Exercise 1 - Find the sine of all the numbers in d


In [80]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [81]:
d = np.array(d)

In [82]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

### Exercise 2 - Find the cosine of all the numbers in d

In [84]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

### Exercise 3 - Find the tangent of all the numbers in d

In [86]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

### Exercise 4 - Find all the negative numbers in d

In [88]:
d[d < 0]

array([-90, -30, -45, -45])

### Exercise 5 - Find all the positive numbers in d

In [90]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

### Exercise 6 - Return an array of only the unique numbers in d.

In [92]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

### Exercise 7 - Determine how many unique numbers there are in d.

In [94]:
np.unique(d).size

11

### Exercise 8 - Print out the shape of d.

In [96]:
d.shape

(3, 6)

### Exercise 9 - Transpose and then print out the shape of d.

In [98]:
d.T.shape

(6, 3)

In [100]:
np.prod(d)

0

### Exercise 10 - Reshape d into an array of 9 x 2

In [101]:
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

In [102]:
x = np.array([1, 2, 3])
y = np.array([0, 1, 2])

np.dot(x, y)

8